// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://iyopsrubmshffdstqbhs.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5b3BzcnVibXNoZmZkc3RxYmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNzc0NDIsImV4cCI6MjA0ODc1MzQ0Mn0.c2wqYeMlEfxU_jZQnwoOLwRtCR8Ga5k4nJiesCgB0nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);